version: "3.8"
services:
  postgresql:
    image: postgres:15.3-alpine3.18
    ports:
      - ${POSTGRES_PORT-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE-postgres}
    volumes:
      - ./postgresql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
