apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-postgresql-initdb-scripts-configmap"
  labels:
    app: "{{ .Release.Name }}"
data:
  create_tables: {{.Files.Get "./postgresql/create_tables.sql"}}
