apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
type: Opaque
stringData:
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
  POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password }}"
  POSTGRES_DATABASE: "{{ .Values.postgresql.auth.database }}"
