port: 3000

postgresql:
  auth:
    database: "nestjs-app-template"
    username: "nestjs-app-template"
  primary:
    initdb:
      scripts-configmap: "nestjs-app-template-postgresql-initdb-scripts"
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"

image:
  repository: null

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"
